### PR TITLE
Images optimization

### PR DESCRIPTION
**Pull request by mark-a-wilson**
Per the B.C. Government **[Accessibility & Inclusion Toolkit](https://www2.gov.bc.ca/gov/content/home/accessible-government/toolkit)**, correct/enhance the accessibility of images across the site. 

Commits include: 

* **NEX-77** - making file names (and folders) descriptive and consistently formatted
* **NEX-78** - adding `alt=""` text to all images (some exceptions)
* **NEX-80** - compressing all images to ~≤250KB

### CODE REVIEW

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-50

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-50

**Comment by mark-a-wilson** [comment]
@parulmishra - could you please investigate what has caused my PR not to build? Let me know if I've made errors that need to be corrected. Thank you!

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-50

**Comment by parulmishra** [comment]
> @parulmishra - could you please investigate what has caused my PR not to build? Let me know if I've made errors that need to be corrected. Thank you!

@mark-a-wilson Try redeploying

**Review by parulmishra — CHANGES_REQUESTED** [review]
There are some build errors. Make sure your branch is in sync with develop and redeploy.

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-50

**Comment by mark-a-wilson** [comment]
Build failed due to this branch being behind `develop`, in which changes had been made to the pipeline. Will start with a new, fresh branch off of `develop` and re-submit.

**Pull request closed without merging**
