### PR TITLE
Nex 24

### PR DESCRIPTION
**Pull request by thegentlemanphysicist**
This implements the Exchange Lab page with a responsive design and timeline.  
I will polish up the code a bit today, but the feature is ready for review

### CODE REVIEW

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-21

**Review by parulmishra — CHANGES_REQUESTED** [review]
@thegentlemanphysicist the navbar in the https://bcdevexchange-dev-21-ifttgq-dev.pathfinder.gov.bc.ca/ has changed (height is increased).

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-21

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-21

**Comment by thegentlemanphysicist** [comment]
> @thegentlemanphysicist the navbar in the https://bcdevexchange-dev-21-ifttgq-dev.pathfinder.gov.bc.ca/ has changed (height is increased).

This should be fixed.  :)

**Review by parulmishra — APPROVED** [review]

**Pull request merged**
