### PR TITLE
Nex 64 jon

### PR DESCRIPTION
**Pull request by thegentlemanphysicist**
I removed the tag helpers so we could use optional parameters with the view components.  
I implemented the styling suggested for the social media links and included the social media links
I did *Not* use branch Nex-64 as a base for this since the task was already started when that branch was created and the branch contains unmerged code from Nex-62.

### CODE REVIEW

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-42

**Review by mark-a-wilson — DISMISSED** [review]
Thanks @thegentlemanphysicist - I like the way you did the changes. I hope I didn't mess anything up - but it looks like the minor styling tweaks I wanted to contribute got picked up OK?

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-42

**Comment by thegentlemanphysicist** [comment]
> Thanks @thegentlemanphysicist - I like the way you did the changes. I hope I didn't mess anything up - but it looks like the minor styling tweaks I wanted to contribute got picked up OK?

I took as much as possible from the NEX-64 branch, however because this was pretty significant refactor there were too many merge conflicts to safely pull the branch NEX-64 into NEX-64-Jon.  I'm hoping that once this PR is in we can retool the styling if anything is missing.

**Review by mark-a-wilson — APPROVED** [review]

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-42

**Pull request merged**
