### PR TITLE
Nex 42

### PR DESCRIPTION
**Pull request by mark-a-wilson**
Hi @parulmishra - This was my attempt to replace the brand image to make it sharper. I fiddled slightly with the stylesheet and html to do this.

### CODE REVIEW

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-23

**Review by parulmishra — DISMISSED** [review]
Just a suggestion: We can also try changing the bcdevexchange's blurry logo in the footer.

**Comment by mark-a-wilson** [comment]
Hi @parulmishra - I attempted to resolve the merge conflict here through the GitHub UI. Can you have another review and let me know if this is OK to merge now?

**Comment by mark-a-wilson** [comment]
Closing this pull request. I'm going to create a fresh branch from `develop` and re-submit this change.

**Pull request closed without merging**
