### PR TITLE
NEX-75 // refactor navbar and its styles

### PR DESCRIPTION
**Pull request by mark-a-wilson**
Refactored the navbar markup and css to fix weird navbar behavior that was happening at screen resolutions 768—992px (see Issue #49). 

- Removed extra `header-area` markup that had been originally created around default Bootstrap `navbar` markup. 
- Removed `header-area` styles from the CSS and added necessary overrides for the default Bootstrap `navbar` styles.
- Also changed the markup and styles for the Digital Marketplace banner that sits above navbar.

### CODE REVIEW

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-52

**Review by parulmishra — COMMENTED** [review]
Since there is no design/mock available for this refactoring. I will be using the deployment to review this PR. As per the deployment https://bcdevexchange-dev-52-ifttgq-dev.pathfinder.gov.bc.ca/ the styling looks a little off to me. The heading on the top of the card are a off-style (not sure if this is what we want). I have a few questions as well: 
1) Is there a specific reason to change the content style of the card on the home page?
2) Since the background for the cards is white, are we not following the black theme for the devops and exchange lab page?

**Comment by parulmishra** [comment]
SonarQube Analysis: https://sonarqube-ifttgq-tools.pathfinder.gov.bc.ca/dashboard?id=BCDevExchange-PR-52

**Comment by mark-a-wilson** [comment]
Thanks for the review, @parulmishra. 

**Re: layout of teasers on the homepage being messed up**
I discovered a missing `}` in the css file which will clean this up. (See https://github.com/bcgov/bcdevexchange/pull/52/commits/d97f149edc87bc442a41f0bd65aef2174c590eb3 I've just added. I don't think a new build gets triggered when I add a commit to an existing PR, does it? If not, I guess you'll have to run this branch locally to verify the fix.)

**Re: using white backgrounds**
Yes, this was an off the cuff design decision I made with some previous branches. I did not ask Inderdeep to make mocks of this, I just went ahead and did it.

This PR is limited to refactoring the navbar and the Digital Marketplace banner at the top.

**Review by parulmishra — APPROVED** [review]

**Pull request merged**
